sudo: required
services:
  - docker

before_install:
  - docker build -t katedelikat/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true katedelikat/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "Docker-env-1.eba-rsazzkid.eu-central-1.elasticbeanstalk.com"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


language: generic